"""Focused controls for the RRSI-to-OpenLine promotion adapter.

Run in this repo's unittest style (CI: python -m unittest discover):

  expected optimizer signer -> accept
  different signer           -> refuse before the operator's checks run
  changed base               -> refuse (C1)
  bad dependency             -> refuse (C3), and install refused without acceptance
  exact accepted artifact    -> install, invoke, signed receipt with loaded digest
  substituted artifact       -> next gated invocation refused
  revocation                 -> next gated invocation refused

The synthetic fixture component is read from the pinned upstream RRSI
source: the RRSI_REPO env var, or ~/workspace/vendor/rrsi. The tests skip
with a clear message when the pinned commit is unavailable there.
"""
from __future__ import annotations

import importlib.util
import io
import json
import os
import subprocess
import tempfile
import unittest
from contextlib import redirect_stderr, redirect_stdout
from pathlib import Path

DEMO_DIR = Path(__file__).resolve().parent.parent / "demo" / "rrsi-promotion-adapter"
_spec = importlib.util.spec_from_file_location("rrsi_promote", DEMO_DIR / "promote.py")
promote = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(promote)

UPSTREAM_PIN = "e4d1a7a0388e02b388bc40eb0a125fcfc7123f8d"
COMPONENT = "third_party/harbor_terminus2/terminus_json_plain_parser.py"
ARTIFACT_FILENAME = "terminus_json_plain_parser.py"
RRSI_REPO = os.environ.get("RRSI_REPO") or str(Path.home() / "workspace" / "vendor" / "rrsi")


def _upstream_component() -> bytes:
    """Byte-read the component from the pinned upstream commit. Never a
    network call when the checkout is local; skips clearly when absent."""
    r = subprocess.run(
        ["git", "-C", RRSI_REPO, "cat-file", "-e", UPSTREAM_PIN + "^{commit}"],
        capture_output=True,
    )
    if r.returncode != 0:
        raise unittest.SkipTest(
            "pinned upstream commit %s not available in RRSI_REPO=%s; "
            "clone it with: git clone https://github.com/google-research/rrsi "
            "<dir> && git checkout %s" % (UPSTREAM_PIN, RRSI_REPO, UPSTREAM_PIN)
        )
    r = subprocess.run(
        ["git", "-C", RRSI_REPO, "show", "%s:%s" % (UPSTREAM_PIN, COMPONENT)],
        capture_output=True,
    )
    if r.returncode != 0 or not r.stdout:
        raise unittest.SkipTest(
            "component %s not readable at pinned commit %s" % (COMPONENT, UPSTREAM_PIN)
        )
    return r.stdout


class PromotionAdapterCase(unittest.TestCase):
    def setUp(self) -> None:
        self.component_bytes = _upstream_component()
        self.tmp = tempfile.TemporaryDirectory()
        self.t = Path(self.tmp.name)
        self.fix = self.t / "fixture-harness"
        self._build_fixture()
        self.home = self.t / "home"
        self._run("init", "--home", str(self.home))
        self._run("set-base", "--home", str(self.home), "--commit", self.base)

    def tearDown(self) -> None:
        self.tmp.cleanup()

    # -- helpers -------------------------------------------------------------

    def _git(self, *args: str) -> str:
        r = subprocess.run(
            ["git", "-c", "user.email=t@localhost", "-c", "user.name=t", *args],
            cwd=str(self.fix), capture_output=True, text=True,
        )
        self.assertEqual(
            r.returncode, 0, "git %s: %s" % (" ".join(args), r.stderr.strip()[-300:])
        )
        return r.stdout.strip()

    def _build_fixture(self) -> None:
        d = self.fix / "third_party" / "harbor_terminus2"
        d.mkdir(parents=True)
        (d / ARTIFACT_FILENAME).write_bytes(self.component_bytes)
        self._git("init", "-q")
        self._git("add", "-A")
        self._git("commit", "-qm", "base: pristine upstream component at %s" % UPSTREAM_PIN)
        self.base = self._git("rev-parse", "HEAD")
        # good candidate: synthetic, behavior-preserving label constant
        comp = self.fix / COMPONENT
        with comp.open("ab") as f:
            f.write(
                b'\n# SYNTHETIC integration-fixture change (NOT generated by RRSI).\n'
                b'PARSER_LABEL = "terminus-json-plain"\n'
            )
        self._git("add", "-A")
        self._git("commit", "-qm", "SYNTHETIC candidate: behavior-preserving label")
        self.good = self._git("rev-parse", "HEAD")
        # bad candidate: adds a non-allowlisted import
        self._git("checkout", "-q", self.base)
        comp.write_text(
            comp.read_text().replace(
                "import json", "import json\nimport socket  # SYNTHETIC: must be rejected", 1
            )
        )
        self._git("add", "-A")
        self._git("commit", "-qm", "SYNTHETIC candidate: adds socket import (must be rejected)")
        self.bad = self._git("rev-parse", "HEAD")
        # moved base + the good change rebased onto it
        self._git("checkout", "-q", self.base)
        (self.fix / "notes.txt").write_text("unrelated")
        self._git("add", "-A")
        self._git("commit", "-qm", "unrelated base change (new incumbent)")
        self.base2 = self._git("rev-parse", "HEAD")
        self._git("cherry-pick", self.good)
        self.good2 = self._git("rev-parse", "HEAD")

    def _run(self, *argv: str):
        out, err = io.StringIO(), io.StringIO()
        with redirect_stdout(out), redirect_stderr(err):
            rc = promote.main(list(argv))
        return rc, out.getvalue(), err.getvalue()

    def _export(self, home: Path, candidate: str, base: str, outdir: str) -> Path:
        rc, _out, err = self._run(
            "export", "--home", str(home), "--repo", str(self.fix),
            "--base", base, "--candidate", candidate, "--component", COMPONENT,
            "--out", outdir, "--version", "fixture-1",
            "--candidate-note", "SYNTHETIC integration fixture; not generated by RRSI",
        )
        self.assertEqual(rc, 0, err)
        return Path(outdir)

    def _accept(self, home: Path, pkgdir: Path):
        return self._run("accept", "--home", str(home), str(pkgdir))

    def _accept_good(self, home: Path, pkgdir: Path) -> str:
        rc, out, err = self._accept(home, pkgdir)
        self.assertEqual(rc, 0, err)
        self.assertIn("ACCEPTED", out)
        recs = sorted((home / "receipts").glob("acceptance_*.json"))
        self.assertTrue(recs)
        return json.loads(recs[-1].read_text())["package_hash"]

    def _fresh_input(self) -> str:
        p = self.t / "input.json"
        p.write_text(
            json.dumps(
                {
                    "analysis": "fresh local work",
                    "plan": "parse this response",
                    "commands": [{"keystrokes": "ls\n", "duration": 0.5}],
                    "task_complete": False,
                }
            )
        )
        return str(p)

    # -- tests ---------------------------------------------------------------

    def test_accept_expected_signer(self):
        pkg = self._export(self.home, self.good, self.base, str(self.t / "pkg"))
        self._accept_good(self.home, pkg)

    def test_refuse_different_signer_before_checks(self):
        other = self.t / "home2"
        self._run("init", "--home", str(other))
        pkg = self._export(other, self.good, self.base, str(self.t / "pkg2"))
        rc, out, err = self._accept(self.home, pkg)
        self.assertEqual(rc, 2, out)
        self.assertIn("SIGNER_NOT_PINNED", err)
        # the refusal happens before the operator's checks run
        self.assertNotIn("C1_base_pinned", out + err)
        # no acceptance decision was recorded for the refused package
        decisions = json.loads((self.home / "decisions.json").read_text())
        ph = promote.package_hash(
            (pkg / ARTIFACT_FILENAME).read_bytes(),
            json.loads((pkg / "manifest.json").read_text()),
        )
        self.assertNotIn(ph, decisions)

    def test_refuse_changed_base(self):
        pkg = self._export(self.home, self.good2, self.base2, str(self.t / "pkg3"))
        rc, out, err = self._accept(self.home, pkg)
        self.assertEqual(rc, 2, out)
        self.assertIn("REJECTED", out)
        self.assertIn("C1_base_pinned: FAIL", out)

    def test_refuse_bad_dependency(self):
        pkg = self._export(self.home, self.bad, self.base, str(self.t / "pkg4"))
        rc, out, err = self._accept(self.home, pkg)
        self.assertEqual(rc, 2, out)
        self.assertIn("REJECTED", out)
        self.assertIn("C3_interface: FAIL", out)
        rc2, _out2, err2 = self._run("install", "--home", str(self.home), str(pkg))
        self.assertEqual(rc2, 2)
        self.assertIn("IMPORT_REFUSED", err2)

    def test_install_invoke_exact_artifact(self):
        pkg = self._export(self.home, self.good, self.base, str(self.t / "pkg5"))
        ph = self._accept_good(self.home, pkg)
        rc, out, err = self._run("install", "--home", str(self.home), str(pkg))
        self.assertEqual(rc, 0, err)
        rc, out, err = self._run(
            "invoke", "--home", str(self.home), ph, "--input", self._fresh_input()
        )
        self.assertEqual(rc, 0, err)
        self.assertIn("loaded digest", out)
        recs = list((self.home / "receipts").glob("invocation_*.json"))
        self.assertTrue(recs)

    def test_refuse_substituted_artifact(self):
        pkg = self._export(self.home, self.good, self.base, str(self.t / "pkg6"))
        ph = self._accept_good(self.home, pkg)
        rc, _out, err = self._run("install", "--home", str(self.home), str(pkg))
        self.assertEqual(rc, 0, err)
        # substitute the deployed bytes outside the install path
        deployed = self.home / "deployment" / "components" / ARTIFACT_FILENAME
        deployed.write_bytes(b"# substituted artifact\n")
        rc, _out, err = self._run(
            "invoke", "--home", str(self.home), ph, "--input", self._fresh_input()
        )
        self.assertEqual(rc, 2)
        self.assertIn("INVOCATION_BINDING_MISMATCH", err)

    def test_revocation_refuses_next_invocation(self):
        pkg = self._export(self.home, self.good, self.base, str(self.t / "pkg7"))
        ph = self._accept_good(self.home, pkg)
        rc, _out, err = self._run("install", "--home", str(self.home), str(pkg))
        self.assertEqual(rc, 0, err)
        rc, _out, err = self._run("revoke", "--home", str(self.home), ph)
        self.assertEqual(rc, 0, err)
        rc, _out, err = self._run(
            "invoke", "--home", str(self.home), ph, "--input", self._fresh_input()
        )
        self.assertEqual(rc, 2)
        self.assertIn("MANDATE_REVOKED", err)


if __name__ == "__main__":
    unittest.main()
