#!/usr/bin/env bash
# RRSI-to-OpenLine promotion adapter: runnable local demonstration.
# Zero paid model calls. Single host. Everything below is deterministic.
set -uo pipefail

DEMO_DIR="$(cd "$(dirname "$0")" && pwd)"
WORK="${1:-$DEMO_DIR/work}"
# RRSI_REPO points at a checkout of google-research/rrsi that contains the
# pinned commit. Override it if your clone lives elsewhere:
#   export RRSI_REPO="$HOME/workspace/vendor/rrsi"
RRSI_REPO="${RRSI_REPO:-$HOME/workspace/vendor/rrsi}"
UPSTREAM_PIN="e4d1a7a0388e02b388bc40eb0a125fcfc7123f8d"
COMPONENT="third_party/harbor_terminus2/terminus_json_plain_parser.py"

if ! git -C "$RRSI_REPO" cat-file -e "$UPSTREAM_PIN^{commit}" >/dev/null 2>&1; then
  echo "fatal: pinned upstream commit $UPSTREAM_PIN is not available in RRSI_REPO=$RRSI_REPO" >&2
  echo "fetch it with:" >&2
  echo "  git clone https://github.com/google-research/rrsi \"\$RRSI_REPO\"" >&2
  echo "  git -C \"\$RRSI_REPO\" checkout $UPSTREAM_PIN" >&2
  exit 1
fi

PROMOTE=(python3 "$DEMO_DIR/promote.py")
export RRSI_ADAPTER_HOME="$WORK/home"

step() { echo; echo "=== $* ==="; }
expect_fail() { # expect_fail <code-word> <cmd...>
  local word="$1"; shift
  if "$@" >/tmp/qs_out.txt 2>/tmp/qs_err.txt; then
    echo "UNEXPECTED: command succeeded, expected refusal"; cat /tmp/qs_out.txt; return 1
  else
    echo "refused as expected:"; grep -m1 -o "refused \[[A-Z_]*\][^$]*" /tmp/qs_err.txt || tail -2 /tmp/qs_err.txt
    grep -q "$word" /tmp/qs_err.txt || { echo "NOTE: expected refusal word $word not in output"; cat /tmp/qs_err.txt; }
  fi
}

rm -rf "$WORK"; mkdir -p "$WORK"

# --- fixture: a synthetic two-commit candidate repo ---------------------------
step "fixture: build a labeled synthetic candidate repo (NOT from RRSI)"
echo "A promotion adapter for RRSI-style harness candidates, demonstrated with"
echo "a synthetic candidate based on a byte-verified RRSI component."
FIX="$WORK/fixture-harness"
mkdir -p "$FIX/third_party/harbor_terminus2"; git -C "$FIX" init -q
git -C "$FIX" -c user.email=fixture@localhost -c user.name=fixture config user.email fixture@localhost
BASE_FILE="$FIX/$COMPONENT"
git -C "$RRSI_REPO" show "$UPSTREAM_PIN:$COMPONENT" > "$BASE_FILE"
# byte-verify the base file against the pinned upstream commit
A="$(sha256sum "$BASE_FILE" | cut -d' ' -f1)"
B="$(git -C "$RRSI_REPO" show "$UPSTREAM_PIN:$COMPONENT" | sha256sum | cut -d' ' -f1)"
[ "$A" = "$B" ] || { echo "fixture base does not match pinned upstream file"; exit 1; }
echo "base file byte-identical to $UPSTREAM_PIN:$COMPONENT"
git -C "$FIX" add -A
git -C "$FIX" -c user.email=fixture@localhost -c user.name=fixture commit -qm "base: pristine upstream component at $UPSTREAM_PIN"
B0="$(git -C "$FIX" rev-parse HEAD)"
# C_good: synthetic, behavior-preserving change, clearly labeled
cat >> "$BASE_FILE" <<'EOF'

# SYNTHETIC integration-fixture change (NOT generated by RRSI, NOT a claim of
# improvement): a parser label constant. Behavior is unchanged.
PARSER_LABEL = "terminus-json-plain"
EOF
git -C "$FIX" add -A
git -C "$FIX" -c user.email=fixture@localhost -c user.name=fixture commit -qm "SYNTHETIC candidate: add parser label constant (behavior unchanged)"
C_GOOD="$(git -C "$FIX" rev-parse HEAD)"
# C_bad: synthetic change that must fail the operator's dependency gate
git -C "$FIX" checkout -q "$B0"
sed -i 's/^import json$/import json\nimport socket  # SYNTHETIC: must be rejected by the operator/' "$BASE_FILE"
git -C "$FIX" add -A
git -C "$FIX" -c user.email=fixture@localhost -c user.name=fixture commit -qm "SYNTHETIC candidate: adds socket import (must be rejected)"
C_BAD="$(git -C "$FIX" rev-parse HEAD)"
# B0b: a different base (simulates the incumbent moving while a candidate
# was in flight); C_alt is the same good change rebased onto it
git -C "$FIX" checkout -q "$B0"
echo "unrelated note" > "$FIX/notes.txt"; git -C "$FIX" add -A
git -C "$FIX" -c user.email=fixture@localhost -c user.name=fixture commit -qm "unrelated base change (new incumbent)"
B0B="$(git -C "$FIX" rev-parse HEAD)"
git -C "$FIX" cherry-pick "$C_GOOD" >/dev/null 2>&1 \
  || { echo "cherry-pick of good change onto new base failed"; exit 1; }
C_ALT="$(git -C "$FIX" rev-parse HEAD)"
[ "$C_ALT" != "$B0B" ] || { echo "cherry-pick produced no new commit"; exit 1; }
echo "B0=$B0 C_GOOD=$C_GOOD C_BAD=$C_BAD B0B=$B0B C_ALT=$C_ALT"

# --- operator setup ----------------------------------------------------------
step "1. operator setup: wallet, identities, deployment base"
"${PROMOTE[@]}" init --home "$WORK/home"
"${PROMOTE[@]}" set-base --home "$WORK/home" --commit "$B0"

# --- export / accept / install / invoke the good candidate --------------------
step "2. export candidate (exact base hash + artifact hash), signed by optimizer"
"${PROMOTE[@]}" export --home "$WORK/home" --repo "$FIX" --base "$B0" \
  --candidate "$C_GOOD" --component "$COMPONENT" --out "$WORK/pkg-good" \
  --version "fixture-1" \
  --candidate-note "SYNTHETIC integration fixture; not generated by RRSI; not a claim of improvement"

step "3. operator acceptance checks (base pin, allowlist, interface, smoke)"
"${PROMOTE[@]}" accept --home "$WORK/home" "$WORK/pkg-good"
PH="$(python3 - "$WORK/home/receipts" <<'EOF'
import glob, json, sys
recs = sorted(glob.glob(sys.argv[1] + "/acceptance_*.json"))
d = json.load(open(recs[-1]))
assert d["decision"] == "accepted", d
print(d["package_hash"])
EOF
)"
echo "package_hash=$PH"

step "4. install: only the exact accepted artifact enters the protected runtime"
"${PROMOTE[@]}" install --home "$WORK/home" "$WORK/pkg-good"

step "5. invoke on fresh local work; loaded digest recorded in signed receipt"
python3 - "$WORK/fresh-input.json" <<'EOF'
import json, sys, uuid
json.dump({
    "analysis": "fresh local work %s" % uuid.uuid4().hex,
    "plan": "parse this response",
    "commands": [
        {"keystrokes": "git status\n", "duration": 0.8},
        {"keystrokes": "git diff --stat\n", "duration": 0.6},
    ],
    "task_complete": False,
}, open(sys.argv[1], "w"))
EOF
"${PROMOTE[@]}" invoke --home "$WORK/home" "$PH" --input "$WORK/fresh-input.json"

# --- bypass attempts: all refused ------------------------------------------------
step "6a. changed base: candidate built on a moved incumbent is refused"
"${PROMOTE[@]}" export --home "$WORK/home" --repo "$FIX" --base "$B0B" \
  --candidate "$C_ALT" --component "$COMPONENT" --out "$WORK/pkg-altbase" \
  --version "fixture-alt" \
  --candidate-note "SYNTHETIC: same change, different base (moved incumbent)"
if "${PROMOTE[@]}" accept --home "$WORK/home" "$WORK/pkg-altbase" > /tmp/qs_acc2.txt 2>&1; then
  echo "UNEXPECTED: changed-base candidate accepted"; cat /tmp/qs_acc2.txt; exit 1
fi
grep -q "REJECTED" /tmp/qs_acc2.txt && grep -q "C1_base_pinned: FAIL" /tmp/qs_acc2.txt \
  && echo "refused as expected (C1_base_pinned FAIL: candidate base != deployed base)" \
  || { echo "unexpected rejection output"; cat /tmp/qs_acc2.txt; exit 1; }

step "6b. rejected candidate: fails the dependency gate, install refused"
"${PROMOTE[@]}" export --home "$WORK/home" --repo "$FIX" --base "$B0" \
  --candidate "$C_BAD" --component "$COMPONENT" --out "$WORK/pkg-bad" \
  --version "fixture-bad" \
  --candidate-note "SYNTHETIC: adds a socket import; must fail operator checks"
if "${PROMOTE[@]}" accept --home "$WORK/home" "$WORK/pkg-bad" > /tmp/qs_acc.txt 2>&1; then
  echo "UNEXPECTED: bad candidate accepted"; cat /tmp/qs_acc.txt; exit 1
fi
grep -q "REJECTED" /tmp/qs_acc.txt && grep -q "C3_interface: FAIL" /tmp/qs_acc.txt \
  && echo "rejected as expected (C3_interface FAIL)" \
  || { echo "unexpected rejection output"; cat /tmp/qs_acc.txt; exit 1; }
expect_fail "IMPORT_REFUSED" "${PROMOTE[@]}" install --home "$WORK/home" "$WORK/pkg-bad"

step "6c. guarded promotion path: a non-operator caller is refused"
expect_fail "GUARDED_PROMOTION_WRITE_DENIED" "${PROMOTE[@]}" bypass --home "$WORK/home" guarded-write

step "6d. substituted artifact: next gated invocation detects the mismatch"
"${PROMOTE[@]}" bypass --home "$WORK/home" substitute
expect_fail "INVOCATION_BINDING_MISMATCH" "${PROMOTE[@]}" invoke --home "$WORK/home" "$PH" --input "$WORK/fresh-input.json"

# --- restore, then revocation ----------------------------------------------------
step "7. restore the accepted artifact, then revoke; next invoke refused"
"${PROMOTE[@]}" revoke --home "$WORK/home" "$PH"
"${PROMOTE[@]}" install --home "$WORK/home" "$WORK/pkg-good" >/dev/null
"${PROMOTE[@]}" revoke --home "$WORK/home" "$PH"
expect_fail "MANDATE_REVOKED" "${PROMOTE[@]}" invoke --home "$WORK/home" "$PH" --input "$WORK/fresh-input.json"

echo
echo "demo complete: promotion stayed under operator control at every step."
echo "proof ceiling: operator-controlled promotion flow, not adversarial isolation."
echo "work dir: $WORK"
